# Generated by Django 4.1 on 2022-08-07 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coffee", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("weight", models.IntegerField()),
                ("price", models.IntegerField()),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Out of Stock"), (1, "In Stock")], default=0
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
